#if !canImport(ObjectiveC)
import XCTest

extension HelloLibTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelloLibTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HelloLibTests.__allTests__HelloLibTests),
    ]
}
#endif
